[package]
name = "EZPass"
version = "0.1.0"
edition = "2021"
<<<<<<< HEAD
=======
description = "Secure password manager built with rust."
authors = ["XTassy"]
homepage = "https://ezpassprogram.vercel.app/"
>>>>>>> bd9a5f0 (final version)

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.34.0", features = ["bundled"] }
winres = "0.1.12"
argon2 = { version = "0.5.3", features = ["password-hash"] }
anyhow = "1.0.97"
sha2 = "0.10.8"
rfd = "0.15.3"
diesel ="2.2.8"
<<<<<<< HEAD
slint = { version = "=1.10.0", default-features = false, features = [
=======
slint = { version = "1.10.0", default-features = false, features = [
>>>>>>> bd9a5f0 (final version)
    "std",
    "renderer-skia",
    "backend-winit",
    "compat-1-2"
] }
block-modes = "0.9.1"
belt-ctr = "0.1.0"
ctr = "0.9.2"
cipher = "0.4.4"
dirs = "6.0.0"
tokio = { version = "1.44.1", features = ["full"] }
orion = "0.17.9"
r2d2 = "0.8.10"
tokio-tungstenite = "0.26.2"
r2d2_sqlite = "0.27.0"
futures-util = "0.3.31"
serde = "1.0.219"
serde_json = "1.0.140"
url = "2.5.4"
rand = "0.8.5"
publicsuffix = "2.3.0"
regex = "1.11.1"
once_cell= "*"
serde_derive = "1.0.219"
winreg = "0.55.0"
embed-resource = "3.0.2"
aes-gcm = "0.10.3"
hex = "0.4.3"
simple_crypt = "0.2.3"
<<<<<<< HEAD



=======
tokio-macros = "2.5.0"
tray-icon = "0.20.0"

[package.metadata.wix]
eula = false
>>>>>>> bd9a5f0 (final version)


[build-dependencies]
slint-build = "1.10.0"
winres = "0.1.12"
image = "0.25.5"
embed-resource = "3.0.2"
