name: Build Cross-Platform
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: EZPass
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: EZPass.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: EZPass
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: EZPass
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: EZPass-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.binary }}
